{
 "title": "UzedoInternal",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "operatorCode", "label": "Код оператора", "query": { "query": "label_values(operatorCode)" } },
   { "name": "organizationId", "label": "Идентификатор организации", "query": { "query": "label_values(organizationId)" } },
   { "name": "job", "label": "Проект", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Общие показатели работы приложения",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Загрузка CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "system_cpu_usage{job=~\"$job\"} * 100",
       "legendFormat": "CPU_USAGE"
      }
     ]
    },
    {
     "title": "Использование памяти в Мб",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=~'$job'})/1048576",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Количество потоков по состояниям",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{job=~\"$job\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Количество активных потоков (в т.ч. Демонов)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Время, затраченное GC",
     "type": "timeseries",
     "description": "Время затраченное сборщиком мусора с разделением по действиям и причиной сборки",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_max{job=\"$job\"} * 1000",
       "legendFormat": "действие=\"{{action}}\" причина=\"{{cause}}\""
      }
     ]
    },
    {
     "title": "Время снятия логов в UZEDO",
     "type": "timeseries",
     "description": "Необходимо при использовании кастомного скраппера",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "targets": [
      {
       "expr": "metrics_scrape_date{job=~\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "База данных",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество потоков, ожидающих коннект",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "hikaricp_connections_pending{job=~\"$job\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Количество активных коннектов к БД",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "hikaricp_connections_active{job=~\"$job\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Получение документов",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество документов, полученных за 1мин",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "receive_document_count_total{operatorCode=~\"$operatorCode\", organizationId=~\"$organizationId\", job=\"$job\"} - receive_document_count_total{operatorCode=~\"$operatorCode\", organizationId=~\"$organizationId\", job=\"$job\"} offset 1m",
       "legendFormat": "{{operationName}}"
      }
     ]
    },
    {
     "title": "Количество активных поток",
     "type": "timeseries",
     "description": "Выведены операции, связанные с документами",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "shortlived_executor_active_threads{job=~\"$job\", operatorCode=~\"$operatorCode\", organizationId=~\"$organizationId\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Количество завершенных потоков",
     "type": "timeseries",
     "description": "Выведены операции, связанные с документами",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "shortlived_executor_completed_tasks{job=~\"$job\", operatorCode=~\"$operatorCode\", organizationId=~\"$organizationId\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Последняя дата подписания",
     "type": "timeseries",
     "description": "Позволяет узнать за какое число на данный момент затягиваются документы",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "targets": [
      {
       "expr": "document_lastsignaturedate{operatorCode=~\"$operatorCode\", job=~\"$job\", organizationId=~\"$organizationId\"}",
       "legendFormat": "Дата подписания документов"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP-операции",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество активных Http запросов",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "server_request_active_operations{job=~\"$job\"}"
      }
     ]
    },
    {
     "title": "Rate-Limiter: Количество свободных токенов",
     "type": "timeseries",
     "description": "С разделением по API",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "rate_limiter_available_token{job=~\"$job\", organizationId=~\"$organizationId\"}",
       "legendFormat": "{{apiGroup}}"
      }
     ]
    },
    {
     "title": "Rate-Limiter: Максимальное количество доступных токенов",
     "type": "timeseries",
     "description": "С разделением по API",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "rate_limiter_size_token{job=~\"$job\", organizationId=~\"$organizationId\"}",
       "legendFormat": "{{apiGroup}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Операторы ЭДО",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Метрика доступности оператора (Не реализовано на Яндексе)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "expr": "operator_availability{operatorCode=~\"$operatorCode\", organizationId=~\"$organizationId\", job=~\"$job\"}"
      }
     ]
    },
    {
     "title": "Общее количество обращений к оператору (мин)",
     "type": "timeseries",
     "description": "С разделением по операциям и коду ответа",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "http_request_outgoing_seconds_count{operatorCode=~\"$operatorCode\", job=~\"$job\", organizationId=~\"$organizationId\"} - http_request_outgoing_seconds_count{operatorCode=~\"$operatorCode\", job=~\"$job\", organizationId=~\"$organizationId\"} offset 1m",
       "legendFormat": "Операция '{{operation}}', статус={{status}}"
      }
     ]
    },
    {
     "title": "Время работы методов (80% перцентиль)",
     "type": "timeseries",
     "description": "80% перцентиль - такое время, при котором 80% полученных данных меньше или равно данному времени. Простыми словами: мы описываем большинство элементов выборки (80%), игнорируя при этом  аномалии. Вы хотите знать, что в целом у вас запросы отрабатывают за какое-то разумное время. Вот в этой фразе «в целом» на математическом языке заменяется на «какой-то перцентиль», а «разумное время» — это его значение.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "http_request_outgoing_seconds{operatorCode=~\"$operatorCode\", quantile=\"0.8\", organizationId=~\"$organizationId\", job=~\"$job\"}",
       "legendFormat": "Operation '{{operation}}', status={{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Время работы методов",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Максимальное время работы методов",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "method_timed_seconds_max{organizationId=~\"$organizationId\", job=~\"$job\"}",
       "legendFormat": "{{class}}.{{methodName}}"
      }
     ]
    },
    {
     "title": "Время работы методов JpaRepository",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "spring_data_repository_invocations_seconds_max{job=~\"$job\"}",
       "legendFormat": "{{repository}}.{{method}} статус={{state}}"
      }
     ]
    },
    {
     "title": "Количество срабатываний JpaRepository (мин)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "spring_data_repository_invocations_seconds_count{job=~\"$job\"} - spring_data_repository_invocations_seconds_count{job=~\"$job\"} offset 1m",
       "legendFormat": "{{repository}}.{{method}} статус={{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Очереди",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество активных задач очередей",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "executor_active_threads{name=~\"sendSignedOutgoingPrimaryDocumentsPoolName|sendEmailPool|deadLetterHandlerPool|generateRevocationRequestPool|sendSignedIopsHandlerPool|sendInviteDocHandlerPool|iopGenerationHandlerPool\", job=~'$job'}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Скорость выполнения задач (мин)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "executor_completed_tasks_total{name=~\"sendSignedOutgoingPrimaryDocumentsPoolName|sendEmailPool|deadLetterHandlerPool|generateRevocationRequestPool|sendSignedIopsHandlerPool|sendInviteDocHandlerPool|iopGenerationHandlerPool\", job=~'$job'} - executor_completed_tasks_total{name=~\"sendSignedOutgoingPrimaryDocumentsPoolName|sendEmailPool|deadLetterHandlerPool|generateRevocationRequestPool|sendSignedIopsHandlerPool|sendInviteDocHandlerPool|iopGenerationHandlerPool\", job=~'$job'} offset 1m",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Количество сообщений в очереди (Не реализовано в Яндексе)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "queue_size_events{job=~\"$job\"}"
      }
     ]
    },
    {
     "title": "Количество оставшихся задач в очереди",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "executor_queue_remaining_tasks{name=~\"sendSignedOutgoingPrimaryDocumentsPoolName|sendEmailPool|deadLetterHandlerPool|generateRevocationRequestPool|sendSignedIopsHandlerPool|sendInviteDocHandlerPool|iopGenerationHandlerPool\", job=~'$job'}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Количество вызовов методов OperatorService (мин)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "method_timed_seconds_count{operatorCode=~\"$operatorCode\", class=\"OperatorServiceImpl\", job=~\"$job\", organizationId=~\"$organizationId\"} - method_timed_seconds_count{operatorCode=~\"$operatorCode\", class=\"OperatorServiceImpl\", job=~\"$job\", organizationId=~\"$organizationId\"} offset 1m",
       "legendFormat": "[{{operatorCode}}] - {{class}}.{{methodName}}"
      }
     ]
    },
    {
     "title": "Время работы методов OperatorService",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "method_timed_seconds{operatorCode=~\"$operatorCode\", class=\"OperatorServiceImpl\", job=~\"$job\", organizationId=~\"$organizationId\", quantile=\"0.8\"}",
       "legendFormat": "[{{operatorCode}}] - {{class}}.{{methodName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Quartz",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Время работы джобов (перцентиль 80%)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "quartz_job_seconds{quantile=\"0.8\", job=~\"$job\", triggerKey=~\".+$organizationId.+\"}",
       "legendFormat": "{{jobClass}}"
      }
     ]
    },
    {
     "title": "Количество обращений в DSS (мин)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "http_request_outgoing_seconds_count{operatorCode=\"undefined\", organizationId=~\"$organizationId\", job=~\"$job\"} - http_request_outgoing_seconds_count{operatorCode=\"undefined\", organizationId=~\"$organizationId\", job=~\"$job\"} offset 1m",
       "legendFormat": "{{operation}}, статус {{status}}"
      }
     ]
    },
    {
     "title": "Количество активных потоков Quartz'а",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "executor_active_threads{name=~\"QuartzThreadPool\", job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "executor_pool_core_threads{name=\"QuartzThreadPool\", job=\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  }
 ]
}